services:
  - type: web
    name: quizboom
    runtime: python
    buildCommand: "pip install -r requirements.txt && python import_questions.py"
    startCommand: "gunicorn app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0